table dim_sexo
	lineageTag: 899ecd9a-1e8c-541e-9294-6b6ab3ada865

	column sexo_key
		dataType: int64
		lineageTag: 3e937284-31a5-5367-8193-6867720d1a40
		summarizeBy: none
		sourceColumn: sexo_key

		annotation SummarizationSetBy = Automatic

	column codigo_sexo
		dataType: string
		lineageTag: 85424ddb-5a7b-547d-9db1-5f1621a055c2
		summarizeBy: none
		sourceColumn: codigo_sexo

		annotation SummarizationSetBy = Automatic

	column nombre_sexo
		dataType: string
		lineageTag: 1e574dc3-c166-58a6-9777-d15b890a00a3
		summarizeBy: none
		sourceColumn: nombre_sexo

		annotation SummarizationSetBy = Automatic

	partition dim_sexo = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(RutaCSV & "dim_sexo.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				    Tipos = Table.TransformColumnTypes(Encabezados, {{"sexo_key", Int64.Type}, {"codigo_sexo", type text}, {"nombre_sexo", type text}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

